# Generated by Django 4.1 on 2023-03-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='title',
            new_name='titre',
        ),
    ]
